In [ ]:
import numpy as np

# Estimación Teórica

In [ ]:
X = np.array([[20,10],[17,22]])
Y = np.array([[350],[500]])

In [ ]:
theta =np.linalg.inv(X.T @ X) @ (X.T @ Y)
theta

array([[10.],
       [15.]])

In [ ]:
np.array([[3,8],[4,30]]) @ theta


array([[150.],
       [490.]])

In [ ]:
TT = np.array([[-9],[1]])
mu = 0.001
for i in range(1000):
  TT = TT + mu*((X.T @ Y) - (X.T@X)@TT)
  print('iter:%2d - x:%2.4f, y:%2.4f'%(i,TT[0],TT[1]))

iter: 0 - x:12.1270, y:20.0820
iter: 1 - x:7.7444, y:15.8932
iter: 2 - x:8.7858, y:16.6663
iter: 3 - x:8.6659, y:16.3901
iter: 4 - x:8.7872, y:16.3440
iter: 5 - x:8.8513, y:16.2553
iter: 6 - x:8.9222, y:16.1815
iter: 7 - x:8.9866, y:16.1101
iter: 8 - x:9.0476, y:16.0435
iter: 9 - x:9.1048, y:15.9808
iter:10 - x:9.1586, y:15.9218
iter:11 - x:9.2092, y:15.8664
iter:12 - x:9.2567, y:15.8143
iter:13 - x:9.3014, y:15.7654
iter:14 - x:9.3434, y:15.7194
iter:15 - x:9.3829, y:15.6762
iter:16 - x:9.4200, y:15.6355
iter:17 - x:9.4548, y:15.5973
iter:18 - x:9.4876, y:15.5614
iter:19 - x:9.5184, y:15.5277
iter:20 - x:9.5473, y:15.4960
iter:21 - x:9.5745, y:15.4661
iter:22 - x:9.6001, y:15.4381
iter:23 - x:9.6241, y:15.4118
iter:24 - x:9.6467, y:15.3870
iter:25 - x:9.6680, y:15.3638
iter:26 - x:9.6879, y:15.3419
iter:27 - x:9.7067, y:15.3214
iter:28 - x:9.7243, y:15.3021
iter:29 - x:9.7409, y:15.2839
iter:30 - x:9.7565, y:15.2668
iter:31 - x:9.7711, y:15.2508
iter:32 - x:9.7849, y:15.2357
iter:33 -

In [ ]:
TT + mu*((X.T @ Y) - (X.T@X)@TT)
TT

array([[4.76827035],
       [4.54303626]])